project:
  type: website

website:
  title: "Larissa Lang"
  #site-url:
  description: "Yet another try creating my website."
  #favicon:
  back-to-top-navigation: true
  # comments section for others to comment
  #   utterances:
  #     repo: lalarus/itsme
  #     label: utterances
  #     theme: body-light
  #     issue-term: title


  navbar:
  #  background: "#ecf0f1"
  # logo:
  # tools:
  # - icon: github
  #   href: https://www.github.com/lalarus
    right:
      - text: Home
        href: index.qmd
      - text: About
        href: about/index.qmd
      - text: Portfolio
        href: portfolio/index.qmd
      - text: Blog
        href: blog/index.qmd   
      - text: Contact
        href: contact.qmd  
    pinned: false

  page-footer:
    left: >-
      &#169; 2023 {{< iconify line-md coffee-loop >}} Larissa Lang, Stockholm<br>  
      Made with [Quarto](https://quarto.org)
    center: ""
    right:
      - text: "I do not track you."
        aria-label: "Accessibility Commitment"
        href: accessibility.qmd
      - text: "Imprint"
        aria-label: "Imprint"
        href: "imprint.qmd"
      - text: "License"
        aria-label: "License Details"
        href: license.qmd



format:
  html:
    theme: 
      - flatly
      - scss/larry-theme-light.scss


    toc: true
