project:
  type: website
  resources:
    - assets/website-texture.mp4

website:
  title: "Larissa Lang"
  #site-url:
  description: "Yet another try creating my website."
  favicon: assets/img/favicon.ico
  back-to-top-navigation: true

  navbar:
    right:
      - text: Home
        href: index.qmd
      - text: About
        href: about/index.qmd
      - text: Portfolio
        href: portfolio/index.qmd  
    pinned: false

  page-footer:
    left: >-
      &#169; 2024 {{< iconify line-md coffee-loop >}} Larissa Lang, Stockholm<br>  
      Made with [Quarto](https://quarto.org)
    center: ""
    right:
      - text: "I do not track you."
        aria-label: "Accessibility Commitment"
        href: accessibility.qmd
#      - text: "Imprint"
#        aria-label: "Imprint"
#        href: "imprint.qmd"
      - text: "License"
        aria-label: "License Details"
        href: license.qmd

format:
  html:
    theme: 
      - flatly
      - scss/larry-theme-light.scss

    link-external-newwindow: true
    # treat links that start with http://www.larissalang.com or http://www.lalarus.github.io as internal links
    link-external-filter: '^(?:http:|https:)\/\/(www\.)*(larissalang\.com|lalarus\.github\.io)\/.*$'

    back-to-top-navigation: true
    toc: true
    toc-depth: 5
    callout-icon: false
