---
title: "Hallo!"
patetitle: "Larissa Lang"
toc: false
format:
  html: 
    page-layout: full
#    grid: 
#      body-width: 4096px
---


::: {.grid}

::: {.g-col-8 .text-large}
Welcome to my little corner. 

this is random text. this is random text. this is random text. this is random text.this is random text. this is random text.this is random text. this is random text.this is random text. this is random text.this is random text. this is random text.this is random text. this is random text.this is random text. this is random text.this is random text. this is random text.this is random text. this is random text.this is random text. this is random text.this is random text. this is random text.this is random text. this is random text.this is random text. this is random text.this is random text. this is random text.this is random text. this is random text.this is random text. this is random text.this is random text. this is random text.this is random text. this is random text.this is random text. this is random text.this is random text. this is random text.this is random text. this is random text.this is random text. this is random text.this is random text. this is random text.this is random text. this is random text.this is random text. this is random text.this is random text. this is random text.this is random text. this is random text.this is random text. this is random text.this is random text. this is random text.this is random text. this is random text.this is random text. this is random text.this is random text. this is random text.this is random text. this is random text.this is random text. this is random text.this is random text. this is random text.

- acessibility: fig-alt text
- images: keeping size small, default ratio 5:3



[Learn more about me &#x2197;](about.qmd)

<!-- [Learn more about me &#x2197;](about.qmd){.btn .btn-outline-primary .btn-lg .btn role="button"}
-->

:::

:::{.g-col-4}
random text.this is random text. this is random text.this is random text. this is random text.this is random text. this is random text.this is random text. this is random text.this is random text. this is random text.this is random text. this is random text.this is random text. this is random text.this is random text. this is random text.this is random text. this is random text.this is random text. this is random text.this is random text. this is random text.this is random text. this is 

:::

:::